var zwemmers = [
  {
    "athlete": "Inge de Bruijn",
    "age": 30,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 1,
    "silver": 1,
    "bronze": 2,
    "total": 4
  },
  {
    "athlete": "Inge de Bruijn",
    "age": 27,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 3,
    "silver": 1,
    "bronze": 0,
    "total": 4
  },
  {
    "athlete": "Pieter van den Hoogenband",
    "age": 22,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 2,
    "silver": 0,
    "bronze": 2,
    "total": 4
  },
  {
    "athlete": "Ranomi Kromowidjojo",
    "age": 21,
    "country": "Netherlands",
    "year": 2012,
    "date": "12/08/2012",
    "sport": "Swimming",
    "gold": 2,
    "silver": 1,
    "bronze": 0,
    "total": 3
  },
  {
    "athlete": "Pieter van den Hoogenband",
    "age": 26,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 1,
    "silver": 2,
    "bronze": 0,
    "total": 3
  },
  {
    "athlete": "Marleen Veldhuis",
    "age": 33,
    "country": "Netherlands",
    "year": 2012,
    "date": "12/08/2012",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 1,
    "total": 2
  },
  {
    "athlete": "Inge Dekker",
    "age": 26,
    "country": "Netherlands",
    "year": 2012,
    "date": "12/08/2012",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Femke Heemskerk",
    "age": 24,
    "country": "Netherlands",
    "year": 2012,
    "date": "12/08/2012",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Hinkelien Schreuder",
    "age": 28,
    "country": "Netherlands",
    "year": 2012,
    "date": "12/08/2012",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Inge Dekker",
    "age": 22,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Femke Heemskerk",
    "age": 20,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Ranomi Kromowidjojo",
    "age": 17,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Hinkelien Schreuder",
    "age": 24,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Maarten van der Weijden",
    "age": 27,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Manon van Rooijen",
    "age": 26,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Marleen Veldhuis",
    "age": 29,
    "country": "Netherlands",
    "year": 2008,
    "date": "24/08/2008",
    "sport": "Swimming",
    "gold": 1,
    "silver": 0,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Inge Dekker",
    "age": 18,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Chantal Groot",
    "age": 21,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Johan Kenkhuis",
    "age": 24,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Annabel Kosten",
    "age": 27,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Mark Veens",
    "age": 26,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Marleen Veldhuis",
    "age": 25,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Mitja Zastrow",
    "age": 27,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Klaas-Erik Zwering",
    "age": 23,
    "country": "Netherlands",
    "year": 2004,
    "date": "29/08/2004",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Chantal Groot",
    "age": 17,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Thamar Henneken",
    "age": 21,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Johan Kenkhuis",
    "age": 20,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Mark van der Zijden",
    "age": 26,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Wilma van Rijn-van Hofwegen",
    "age": 29,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Manon van Rooijen",
    "age": 18,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 1,
    "bronze": 0,
    "total": 1
  },
  {
    "athlete": "Marcel Wouda",
    "age": 28,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  },
  {
    "athlete": "Martijn Zuijdweg",
    "age": 23,
    "country": "Netherlands",
    "year": 2000,
    "date": "01/10/2000",
    "sport": "Swimming",
    "gold": 0,
    "silver": 0,
    "bronze": 1,
    "total": 1
  }
];